### ISSUE TITLE
Does it has gracefulReload?

### ISSUE THREAD

**Issue by sidneyvav** [indutny/sticky-session#44] opened 2016-02-25 18:21 UTC
I used to have PM2 on cluster mode. So with gracefulReload I can reload the application with 0 downtime. As I can't use sticky-session with PM2's cluster, I now use PM2 on fork and cluster with node. PM2 on fork can't reload with 0 downtime, so is it possible to do with sticky-session's cluster ?

**Comment by indutny** [comment] 2016-02-26 00:06
There are currently no APIs for this. If you are interested I could give some hints on how it could be implemented.

Sorry!

**Comment by sidneyvav** [comment] 2016-02-26 16:58
Actually I'm very interested, I'll fork the project and work on it!

**Comment by kevinresol** [comment] 2016-05-31 10:20
Seems that using `server.emit('connection', socket)` does not add a counter to `server.getConnections()`. In other words, the server does not keep track of the number of active connections. This causes `server.close()` to finish immediately without waiting for the active connections to end. This breaks graceful shutdown. Any ways to workaround it?

**Comment by indutny** [comment] 2016-06-01 01:07
Should be fixed now, sorry!

**Closed** 2016-06-01 01:06 UTC

**Comment by kevinresol** [comment] 2016-06-01 01:19
@indutny thanks for the quick response. I will give it a try soon. btw, just a side question for curiosity: where do you get information about the private api like `server._connections`?

**Comment by indutny** [comment] 2016-06-01 01:22
I work on node.js core. Though, I agree with you that this kind of hacky. Not sure if cleaner solution is possible without introducing custom `Server` instances.

**Comment by kevinresol** [comment] 2016-06-01 02:42
@indutny Just tried it, I think one more line is needed `socket.server = server;` Not sure if it is related, but I am using a [variation](https://github.com/wzrdtales/socket-io-sticky-session) of this lib. It doesn't reduce the connection count after a connection is done, until I added the forementioned line.

I referenced these code: https://github.com/nodejs/node/blob/7885b1d7aa11434ae5692241ea2fdd4baccd10e5/lib/net.js#L1432-L1434

**Comment by kevinresol** [comment] 2016-06-01 02:47
Hmm... I am still on v4.0.0, maybe that matters.

**Comment by kevinresol** [comment] 2016-06-01 02:56
Well, confirmed v6.2.0 doesn't need `socket.server = server;`.

**Comment by indutny** [comment] 2016-06-01 03:35
Pushed update, looks like I made a typo.
